-- 1
select POE.POE_ID , POE_ARCHIVO.PPARC_NOMBRE , TIPO_DOCUMENT.TDOC_NOMBRE from POE left join 
POE_ARCHIVO on 
POE.POE_ID = POE_ARCHIVO.POE_ID left join TIPO_DOCUMENT on
TIPO_DOCUMENT.TDC_ID = POE_ARCHIVO.TDC_ID order by 1 asc;

-- 2
select POE.POE_ID , DOSIMETRO.DOS_MARCA, DOSIMETRO.DOS_MODELO,DOSIMETRO_TIPO.DTIP_NOMBRE,
POE_CONTROL.PCON_ANIO,POE_CONTROL.PCON_TRIMESTE, POE_CONTROL.PCON_RESULTA
from POE left join DOSIMETRO on POE.POE_ID = DOSIMETRO.POE_ID
left join DOSIMETRO_TIPO on DOSIMETRO_TIPO.DTIP_ID = DOSIMETRO.DTIP_ID 
left join POE_CONTROL on  POE_CONTROL.POE_ID = POE_ID order by 1 asc;


